# DeepVQE Training Configuration

# Model selection
model_type: 'medium'  # 'full' for DeepVQE, 'medium' for DeepVQE_M, 'small' for DeepVQE_S

# Data loading mode: 'local' or 'webdataset'
data_mode: 'webdataset'  # 'local' for local files, 'webdataset' for streaming from HuggingFace Hub

# Local data configuration (when data_mode='local')
data_dir: './data_stft'
train_split: 0.9

# WebDataset configuration (when data_mode='webdataset')
# For HuggingFace Hub: set hf_repo_id and use relative patterns
# For local tars: set hf_repo_id=null and use absolute/relative paths
hf_repo_id: null  # e.g., 'username/deep-vqe-dataset' or null for local
train_tar_pattern: '/workspace/data/train_*.tar.gz'  # Can be string or list
val_tar_pattern: '/workspace/data/val_*.tar.gz'      # Can be string or list
cache_dir: null  # Cache directory for downloaded shards (null = default)

# Training parameters
batch_size: 42
num_epochs: 100
learning_rate: 0.00001  # 1e-5
num_workers: 8
accumulate_gradients: 1

# Loss function configuration
loss_type: 'multi_resolution'  # 'original' or 'multi_resolution'

# Original loss weights (used when loss_type='original')
alpha: 0.7  # Amplitude loss weight
beta: 0.3   # Phase loss weight

# Multi-Resolution Loss weights (used when loss_type='multi_resolution')
# Recommended for echo cancellation + noise reduction:
lambda_sc: 1.0      # Spectral convergence: forces overall spectral shape matching
lambda_mag: 1.0     # Log magnitude: ensures accuracy at all energy levels (quiet + loud)
lambda_sisdr: 0.5   # SI-SDR: time-domain perceptual quality refinement

# Multi-STFT resolutions (captures features at different time scales)
# 512: fast transients (consonants), 1024: pitch/harmonics, 2048: spectral envelope
fft_sizes: [512, 1024, 2048]
hop_sizes: [128, 256, 512]    # hop = fft_size // 4
win_sizes: [512, 1024, 2048]  # typically same as fft_size

# Directories
experiment_name: 'multiloss'  # Subdirectory name for this experiment
checkpoint_dir: './checkpoints'
log_dir: './logs'

# Hardware
accelerator: 'auto'  # 'auto', 'gpu', 'cpu', 'mps', 'cuda'

# HuggingFace Hub auto-upload
hf_checkpoint_repo_id: 'vgodie/deep-vqe-s'  # e.g., 'username/deep-enhancer-checkpoints'
